package com.periodicals.dao.connection;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class ConnectionWrapper implements AutoCloseable {
    private Connection conn;
    private boolean isTransaction;

    public ConnectionWrapper(Connection conn, boolean isTransaction) {
        this.conn = conn;
        this.isTransaction = isTransaction;
    }

    @Override
    public void close() throws Exception {
        if (!isTransaction) {
            conn.close();
        }
    }

    public Connection getConnection() {
        return conn;
    }

    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return conn.prepareStatement(sql);
    }

    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return conn.prepareStatement(sql, autoGeneratedKeys);
    }
}
