package com.periodicals.dao.connection;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * Special connection wrapper that is dividing logic for
 * common and transactional connections
 */
public class ConnectionWrapper implements AutoCloseable {
    private Connection connection;
    private boolean isTransaction;

    ConnectionWrapper(Connection connection, boolean isTransaction) {
        this.connection = connection;
        this.isTransaction = isTransaction;
    }

    @Override
    public void close() throws Exception {
        if (!isTransaction) {
            connection.close();
        }
    }

    public Connection getConnection() {
        return connection;
    }

    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return connection.prepareStatement(sql);
    }

    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return connection.prepareStatement(sql, autoGeneratedKeys);
    }
}
